### ISSUE TITLE
application requires additional permissions that can not be granted

### ISSUE THREAD

**Issue by gaussandhisgun** [reiryuki/Extreme-Battery-Saver-Magisk-Module#1]
Sometimes when tapping on the launcher icon, the app will crash with this error https://paste.evolution-x.org/caqnQT - seemingly asking for a permission that it does not have. I tried granting this permission using root shell and was greeted with "It is not a changeable permission" into my face. xiaomi/curtana, android 12l, project blaze 1.3. application does work as intended when it does not crash

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules
4) Full logcat #logcat
5) Z folder #zscript

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.
