### ISSUE TITLE
ANDROID SIGNATURE VERIFICATION ISSUE

### ISSUE THREAD

**Issue by styeff** [reiryuki/Extreme-Battery-Saver-Magisk-Module#3]
ASV is disabled, but 1.4 module version still check it, not allowing me to install it. Older versions working! (I'm on LOS A13 -surya) details in attachment:
![Screenshot_20230309-161229_Magisk](https://user-images.githubusercontent.com/101471099/224077283-be3c35ae-5792-4fd1-88d3-77caf0ea662b.png)

**Comment by reiryuki** [comment]
That means the signature verification is not disabled correctly. Older version does not checking the required permission correctly, so it can be installed even the permission is not granted but even it's installed, the app will not pause your apps at all if it's activated while battery saver is on.

NB: screenshot is not a log

**Comment by styeff** [comment]
I followed the LSPosed procedure, using Core Patch and XDownloader, may I kindly ask an effective way to disable Android Signature verification? Thanks!

**Comment by reiryuki** [comment]
Try Lucky Patcher's LSPosed mode

**Comment by reiryuki** [comment]
or Lucky Patcher Magisk module mode

**Comment by reiryuki** [comment]
or you can just use any custom ROM AOSP signatured so you don't need to disable signature verification

**Comment by styeff** [comment]
Solved using Lucky Patcher! Thanks for you time!
