### ISSUE TITLE
Enhance HyperOS Support

### ISSUE THREAD

**Issue by vslmc** [reiryuki/Extreme-Battery-Saver-Magisk-Module#9]
Device: Xiaomi 13 (fuxi)
Android: 14
ROM: xiaomi.eu 1.0.13.0.0 (stable)
<br>
Flipendo does work great with HyperOS (xiaomi.eu version).
But there is one hiccup the user needs to resolve befor using this.

HyperOS has two modes to save battery , the default battery saver (BS) and it's own Extreme Battery Saver (EBS) mode. 
For flippendo to work , the system needs to be in EBS mode not BS.

But Xiaomis EBS mode does more than just set a flag; For example it swaps the launcher into a very basic lite version, and freezes some Google apps.
The BS mode on the other hand, does nothing additional

So, in order to work probably it's nessecary to tell the system to use EBS , without starting the other tasks like swapping the launcher.
At the moment a very simple way is to use the root app "s1m.savertuner" to manually set EBS on.

The idea/request in this case would be to somehow modify the flag that get set by BS , to the flag used by EBS. Or modifying Flipendo to be active in BS mode.

In this case the default BS would be the Flipendo EBS, and hyperOS default EBS would be same + any additional task Xiaomi has added.
<br>
Screenshot of working Flipendo on HyperOS:

![Screenshot_2024-09-06-08-37-40-526_com miui home](https://github.com/user-attachments/assets/b0e972cd-634c-4bce-8c74-3a5b15da2660)

**Comment by reiryuki** [comment]
It's not possible
